---
plugin: gcp_compute
keyed_groups:
  - prefix: gcp
    key: labels.awx_role
    groups:
     "{{ item }}": "'{{ item }}' in labels.awx_label"
zones:
  - us-central1-a
  - us-central1-b
  - us-central1-c
projects:
 - {{ project_id }}
hostnames:
  - name
auth_kind: serviceaccount
compose:
  ansible_host: networkInterfaces[0].networkIP